user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name _;
        
        # Gipunting sa public directory sa imong Symfony root folder
        root /var/www/html/public;
        index index.php;

        charset utf-8;

        location / {
            # Gitul-id ang routing para sa Symfony URL standards
            try_files $uri /index.php$is_args$args;
        }

        # Saktong pag-execute sa PHP gamit ang index.php entry point sa Symfony
        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
            internal;
        }

        # Proteksyon aron dili ma-execute ang laing php files sa gawas sa public folder
        location ~ \.php$ {
            return 404;
        }

        error_log /var/log/nginx/project_error.log;
        access_log /var/log/nginx/project_access.log;
    }
}